export const OrderLabels = ['User', 'Location', 'Items'];
export const RegistrationLabels = ['User', 'Set Password', 'Success'];
export const customStyles = {
  stepIndicatorSize: 50,
  currentStepIndicatorSize: 60,
  separatorStrokeWidth: 1,
  currentStepStrokeWidth: 1,
  stepStrokeCurrentColor: '#66E4EE',
  stepStrokeWidth: 1,
  stepStrokeFinishedColor: '#20c997',
  stepStrokeUnFinishedColor: '#66E4EE',
  separatorFinishedColor: '#20c997',
  separatorUnFinishedColor: '#A3A8AE',
  stepIndicatorFinishedColor: '#ffffff',
  stepIndicatorUnFinishedColor: '#ffffff',
  stepIndicatorCurrentColor: '#66E4EE',
  stepIndicatorLabelFontSize: 16,
  currentStepIndicatorLabelFontSize: 16,
  stepIndicatorLabelCurrentColor: '#004666',
  stepIndicatorLabelFinishedColor: '#4C5356',
  stepIndicatorLabelUnFinishedColor: '#4C5356',
  labelColor: '#4C5356',
  labelSize: 14,
  currentStepLabelColor: '#004666',
};
