export enum Colors {
  WHITE = '#FFFFFF',
  BLACK = '#000000',

  PRIMARY_BACKGROUND = '#004666',
  SECONDARY_BACKGROUND = '',
  TERTIARY_BACGKROUND = '#00628F',
  TERTIARY_BRIGHT_BLUE = '#66E4EE',

  PRIMARY_TEXT = '',
  SECONDARY_TEXT = '',

  ICON_RIPPLE_COLOR = 'rgba(0, 17, 26, 0.6)',

  CART_IMAGE_BACGKROUND = '#f0f0f3',
  CART_TEXT_COLOR = '#CCCCCC',
  CART_ORDER_INFO_TEXT_COLOR = '#CCCCCC',

  DANGER_COLOR = '#EB0D3F',
  WARNGING_COLOR = '#F5E850',
  INFO_COLOR = '#0d6efd',
  SUCCESS_COLOR = '#009900',
  WARNING_TEXT_COLOR = '#4C5356',

  SPLASH_COLOR = '#302d2d',

  STAR_SELECTED = '#004666',
  STAR_UNSELECTED = '#D4D6D9',

  BANNER_IMAGE_TEXT_BACKGROUND = '#004666',

  DISABLED_BUTTON = '#A8ADB3',
}
