import {AppTheme} from '../appTheme';
import {Colors} from '../colors';

export const ECOMMERCE_THEME: AppTheme = {
  colors: {
    white: Colors.WHITE,
    black: Colors.BLACK,
    iconRippleColor: Colors.ICON_RIPPLE_COLOR,
    sideMenuBackgroundColor: Colors.PRIMARY_BACKGROUND,
    sideMenuTextColor: Colors.WHITE,
    secondaryBacgkroundColor: Colors.SECONDARY_BACKGROUND,
    primaryTextColor: Colors.PRIMARY_BACKGROUND,
    secondaryTextColor: Colors.SECONDARY_BACKGROUND,
    sideMenuDividerColor: Colors.TERTIARY_BACGKROUND,
    loginButtonBackgroundColor: Colors.TERTIARY_BRIGHT_BLUE,
    loginButtonTextColor: Colors.PRIMARY_BACKGROUND,
    headerIconColor: Colors.PRIMARY_BACKGROUND,
    cartImageBackgroundColor: Colors.CART_IMAGE_BACGKROUND,
    cartTextColor: Colors.CART_TEXT_COLOR,
    orderInfoTextColor: Colors.BLACK,
    checkoutButtonBackgroundColor: Colors.PRIMARY_BACKGROUND,
    cartStatusBarColor: Colors.WHITE,
    openDrawerIconColor: Colors.PRIMARY_BACKGROUND,
    cartIconColor: Colors.PRIMARY_BACKGROUND,
    searchBorderColor: Colors.PRIMARY_BACKGROUND,
    categoriesBackgroundColor: Colors.PRIMARY_BACKGROUND,
    categorisTextColor: Colors.WHITE,
    singleProductStatusBarColor: Colors.CART_IMAGE_BACGKROUND,
    singleProductImageBackgroundColor: Colors.CART_IMAGE_BACGKROUND,
    singleProductTextColor: Colors.BLACK,
    singleProductButtonBakgroundColor: Colors.PRIMARY_BACKGROUND,
    singleProductButtonTextColor: Colors.WHITE,
    singleProductBackIconColor: Colors.PRIMARY_BACKGROUND,
    singleProductSkeletonColor: Colors.CART_IMAGE_BACGKROUND,
    productsSkeletonColor: Colors.CART_IMAGE_BACGKROUND,
    productsImageBackgroundColor: Colors.CART_IMAGE_BACGKROUND,
    productsStatusBarColor: Colors.PRIMARY_BACKGROUND,
    flashMessageDangerBackgroundColors: Colors.DANGER_COLOR,
    flashMessageSuccessBackgroundColors: Colors.SUCCESS_COLOR,
    flashMessageWarningBackgroundColors: Colors.WARNGING_COLOR,
    flashMessageInfoBackgroundColors: Colors.INFO_COLOR,
    flashMessageTextColor: Colors.WHITE,
    splashScreenStatusBarColor: Colors.SPLASH_COLOR,
    favoriteHeartColor: Colors.PRIMARY_BACKGROUND,
    favoriteHeartBorderColor: Colors.PRIMARY_BACKGROUND,
    favoritesTrashColor: Colors.PRIMARY_BACKGROUND,
    favoritesTrashBorderColor: Colors.PRIMARY_BACKGROUND,
    starSelectedColor: Colors.STAR_SELECTED,
    starUnselectedColor: Colors.STAR_UNSELECTED,
  },
};
